from common_request import perform_request

# Define the query parameters
params = {
    'k': [
        "animalid",  # Example return parameter
        "eartag_or_id",
        "state",
        "origin_name",
        "sex",
        "species_name",
        "sacrifice_reason_name",
        "sacrifice_comment",
        "datesacrificed",
        "cagenumber",
        "room_name",
        "building_name",
        "age_days",
        "dateborn",
        "comments",
        "strain_id",
        "strain_name",

        # Unused parameters
        # "pupid",
        # "prefix",
        # "labid",
        # "cohort_id",
        # "rfid",
        # "species_weight_unit",
        # "sacrifice_actor_username",
        # "sacrifice_actor_fullname",
        # "cagetype",
        # "cagelabel",
        # "cage_owner_username",
        # "cage_owner_fullname",
        # "rack_description",
        # "area_name",
        # "responsible_id",
        # "responsible_fullname",
        # "owner_userid",
        # "owner_username",
        # "owner_fullname",
        # "age_weeks",
        # "date_last_comment",
        # "generation",
        # "gen_bg_id",
        # "gen_bg",
        # "strain_name_id",
        # "strain_name_with_id",
        # "mutations",
        # "genetically_modified",
        # "parents",
        # "licence_title",
        # "licence_id",
        # "licence_number",
        # "classification_id",
        # "classification",
        # "pregnant_days",
        # "plug_date",
        # "wean_date",
        # "projects",
        # "requests",
        # "weight",
        # "animal_color",
        # "animal_user_color",
        # "import_order_request_id",
    ],
    's': "species_name:asc",  # Example sort parameter

    # Unused sort parameters (Max 1)
    # "eartag_or_id:asc",
    # "eartag_or_id:desc",
    # "prefix:asc",
    # "prefix:desc",
    # "labid:asc",
    # "labid:desc",
    # "cohort_id:asc",
    # "cohort_id:desc",
    # "origin_name:asc",
    # "origin_name:desc",
    # "sex:asc",
    # "sex:desc",
    # "species_name:asc",
    # "species_name:desc",
    # "datesacrificed:asc",
    # "datesacrificed:desc",
    # "cagenumber:asc",
    # "cagenumber:desc",
    # "cagelabel:asc",
    # "cagelabel:desc",
    # "cage_owner_username:asc",
    # "cage_owner_username:desc",
    # "cage_owner_fullname:asc",
    # "cage_owner_fullname:desc",
    # "rack_description:asc",
    # "rack_description:desc",
    # "room_name:asc",
    # "room_name:desc",
    # "area_name:asc",
    # "area_name:desc",
    # "building_name:asc",
    # "building_name:desc",
    # "responsible_fullname:asc",
    # "responsible_fullname:desc",
    # "owner_username:asc",
    # "owner_username:desc",
    # "owner_fullname:asc",
    # "owner_fullname:desc",
    # "age_days:asc",
    # "age_days:desc",
    # "age_weeks:asc",
    # "age_weeks:desc",
    # "dateborn:asc",
    # "dateborn:desc",
    # "date_last_comment:asc",
    # "date_last_comment:desc",
    # "strain_name:asc",
    # "strain_name:desc",
    # "strain_name_id:asc",
    # "strain_name_id:desc",
    # "strain_name_with_id:asc",
    # "strain_name_with_id:desc",
    # "licence_title:asc",
    # "licence_title:desc",
    # "licence_id:asc",
    # "licence_id:desc",
    # "licence_number:asc",
    # "licence_number:desc",
    # "classification_id:asc",
    # "classification_id:desc",
    # "classification:asc",
    # "classification:desc",
    # "pregnant_days:asc",
    # "pregnant_days:desc",
    # "plug_date:asc",
    # "plug_date:desc",
    # "wean_date:asc",
    # "wean_date:desc",
    # "projects:asc",
    # "projects:desc",
    # "weight:asc",
    # "weight:desc",
    # "import_order_request_id:asc",
    # "import_order_request_id:desc",
    'o': 0,  # Number of items to skip from the beginning
    'l': 100,  # Maximum amount of returned items
    'status': "active"  # Animal status
}

perform_request('/animals', params)