from common_request import perform_request

# Define the query parameters
params = {
    'k': [
        "cageid",
        "cagetype",
        "cagenumber",
        "cagelabel",
        "owner_userid",
        "owner_username",
        "owner_fullname",
        "responsible_id",
        "responsible_fullname",
        "projects",
        "rack_id",
        "room_id",
        "status",
        "num_total",
        "num_males",

        # Unused parameters
        # "category",
        # "creationdate",
        # "terminationdate",
        # "rack",
        # "area_id",
        # "area",
        # "building_id",
        # "building",
        # "num_females",
        # "comments",
        # "male_strain_id",
        # "male_strainname",
        # "female_strain_id",
        # "female_strainname",
        # "pup_strain_id",
        # "pup_strain",
        # "cage_color",
        # "cage_user_color",
    ],
    's': "cagenumber:asc",  # Example sort parameter

        # Unused sort parameters (Max 1)
        # "cagetype:asc",
        # "cagetype:desc",
        # "cagenumber:desc",
        # "cagelabel:asc",
        # "cagelabel:desc",
        # "category:asc",
        # "category:desc",
        # "creationdate:asc",
        # "creationdate:desc",
        # "owner_username:asc",
        # "owner_username:desc",
        # "owner_fullname:asc",
        # "owner_fullname:desc",
        # "projects:asc",
        # "projects:desc",
        # "responsible_fullname:asc",
        # "responsible_fullname:desc",
        # "rack:asc",
        # "rack:desc",
        # "room:asc",
        # "room:desc",
        # "area:asc",
        # "area:desc",
        # "building:asc",
        # "building:desc",
        # "male_strainname:asc",
        # "male_strainname:desc",
        # "female_strainname:asc",
        # "female_strainname:desc",
        # "pup_strain:asc",
        # "pup_strain:desc",
    'o': 0,
    'l': 100,
    'status': "open_or_empty"
}

perform_request('/cages', params)